sudo: false
language: node_js
node_js:
  - "10"
  - "12"
script:
  - npm run lint
  - npm run build
  - npm run test
  - npm run report
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sauce_connect: true
