sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
before_script:
  - echo 'begin tests'
script:
  - npm run lint
  - npm run build
  - make test-travis
  - npm run dist
  - if node --version | grep -c v6 >/dev/null; then make test-browser; fi
after_script:
  - echo "end tests"
after_success:
  - bash <(curl -s https://codecov.io/bash)
addons:
  sauce_connect: true
